export const clubs = [
  { key: "FAIC", label: "FPTU AI Club" },
  { key: "ISC", label: "FPTU I-SKATE CLUB" },
  { key: "FUB", label: "FPTU BASKETBALL CLUB" },
  { key: "FUSW", label: "FU Street Workout" },
  { key: "ESC", label: "ESC - FPTU Esports Club" },
  { key: "FKC", label: "FPTU Karate Club" },
  { key: "FUGYM", label: "FU Gymnastic" },
  { key: "FUVC", label: "FPTU Volleyball Club - CLB Bóng chuyền" },
  { key: "FNC", label: "FPTU Nunchaku club" },
  { key: "FMUC", label: "FPTU Muay Club" },
  { key: "FVC", label: "FPTU VOVINAM CLUB" },
  { key: "FTC", label: "FPTU Taekwondo Club" },
  { key: "FBC", label: "FPTU Badminton Club" },
  { key: "FTTC", label: "FPTU Table Tenis Club" },
  { key: "Soleil", label: "Soleil Crew" },
  { key: "Blazie Dance", label: "FPTU - Blazie Dance" },
  { key: "FGC", label: "FU Guitar Club" },
  { key: "Melody", label: "FPTU-Melody Club" },
  { key: "Color Team", label: "Color Team" },
  { key: "iGo Club", label: "Câu lạc bộ Vì cộng đồng iGo" },
  { key: "FJC", label: "Mây Mưa Club - FPT Japan Club" },
  { key: "M&M", label: "Moviemaniacs - FPTU Acting & Filming Club" },
  { key: "Branché", label: "Branché - FPTU Fashion & Model Club" },
  { key: "FAC", label: "FPTU Art Club" },
  { key: "FBGC", label: "FPTU BoardGame Club" },
  { key: "FUP", label: "FU - Photography" },
  { key: "FPTU Dango Club", label: "FPTU Dango Club" },
  { key: "HEBE CLUB", label: "HEBE CLUB" },
  { key: "FGoC", label: "FPT Go Club - CLB Cờ vây FPT" },
  { key: "FMVC", label: "Câu lạc bộ Võ thuật Điện ảnh" },
  { key: "FJY", label: "FPT Junior Yosakoi" },
  { key: "HFU", label: "Hiphop FPT University" },
  { key: "Chess", label: "FPTU Chess Club" },
  { key: "FCOC", label: "FPTU Cóc Gia Đường Club" },
  { key: "FPC", label: "FPTU Psychology Club" },
  { key: "BUK", label: "FPTU BOOK CLUB" },
  { key: "FTIC", label: "CLB Nhạc Cụ Truyền Thống FTIC" },
  { key: "MonStage", label: "FPTU MonStage Club - CLB MC & Thuyết trình" },
  { key: "EHC", label: "FPTU - Ethical Hackers Club" },
  { key: "FDS", label: "FPTU Data Science Club" },
  { key: "FBC/Business", label: "FPTU Business Club" },
  { key: "FPBC", label: "FPTU pickleball Club" },
  { key: "FCC", label: "CLB Tiếng Trung - Đại Học FPT" },
  { key: "NSC", label: "No Shy Club" },
  { key: "JS Club", label: "Japanese Software Engineers" },
  { key: "FEC", label: "FPTU English Club" },
  { key: "FDC", label: "FPTU Debate Club" },
];

export const plans = [
  { key: "le", label: "Tham dự phần lễ (Miễn phí)" },
  { key: "tiec", label: "Tham dự phần tiệc (190k/người)" },
  { key: "cahai", label: "Cả hai" },
];
