export const clubs = [
  { key: "branche", label: "Branché" },
  { key: "buk", label: "BUK" },
  { key: "chess", label: "Chess" },
  { key: "color_team", label: "Color Team" },
  { key: "ehc", label: "EHC" },
  { key: "esc", label: "ESC" },
  { key: "fac", label: "FAC" },
  { key: "fbc", label: "FBC" },
  { key: "fbc_business", label: "FBC/Business" },
  { key: "fbgc", label: "FBGC" },
  { key: "fco", label: "FCOC" },
  { key: "fcc", label: "FCC" },
  { key: "fec", label: "FEC" },
  { key: "fds", label: "FDS" },
  { key: "fgc", label: "FGC" },
  { key: "fgoc", label: "FGoC" },
  { key: "fjy", label: "FJY" },
  { key: "fkc", label: "FKC" },
  { key: "fmuc", label: "FMUC" },
  { key: "fmvc", label: "FMVC" },
  { key: "fnc", label: "FNC" },
  { key: "fpbc", label: "FPBC" },
  { key: "fpc", label: "FPC" },
  { key: "fptu_dango_club", label: "FPTU Dango Club" },
  { key: "ftc", label: "FTC" },
  { key: "ftic", label: "FTIC" },
  { key: "fttc", label: "FTTC" },
  { key: "fub", label: "FUB" },
  { key: "fugym", label: "FUGYM" },
  { key: "fup", label: "FUP" },
  { key: "fusw", label: "FUSW" },
  { key: "fuvc", label: "FUVC" },
  { key: "fvc", label: "FVC" },
  { key: "hebe_club", label: "HEBE CLUB" },
  { key: "hfu", label: "HFU" },
  { key: "igo_club", label: "iGo Club" },
  { key: "isc", label: "ISC" },
  { key: "js_club", label: "JS Club" },
  { key: "melody", label: "Melody" },
  { key: "mnm", label: "M&M" },
  { key: "monstage", label: "MonStage" },
  { key: "nsc", label: "NSC" },
  { key: "soleil", label: "Soleil" },
  { key: "blazie_dance", label: "Blazie Dance" },
];
